version: "3.9"
services:
  database:
    labels:
      - traefik.enable=false

  web:
    labels:
      - traefik.enable=true
      - traefik.http.routers.laravel_https.rule=Host(`laravel.local`)
      - traefik.http.routers.laravel_https.entryPoints=web
      - traefik.docker.network=linkt

  phpmyadmin:
    labels:
      - traefik.enable=true
      - traefik.http.routers.laravel_phpmyadmin.rule=Host(`phpmyadmin.laravel.local`)
      - traefik.http.routers.laravel_phpmyadmin.entryPoints=web
      - traefik.docker.network=linkt

  node:
    command: npm run watch

  smtp:
    labels:
      - traefik.enable=true
      - traefik.http.routers.laravel_maildev.rule=Host(`maildev.laravel.local`)
      - traefik.http.routers.laravel_maildev.entryPoints=web
      - traefik.http.services.laravel_maildev.loadbalancer.server.port=1080
      - traefik.docker.network=linkt

networks:
  default:
    external:
      name: linkt
